name: 2. Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

    inputs:
      force_build:
        description: 'Force build all apps regardless of patch timestamp'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - 'src/build/**'
      - 'src/patches/**'
      - 'src/options/**'
      - '.github/workflows/**'

jobs:
  check:
    name: Check new patch releases
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    outputs:
      check_morphe: ${{ steps.check-morphe.outputs.new_patch }}
      check_instagram: ${{ steps.check-instagram.outputs.new_patch }}
      force_run: ${{ github.event_name == 'push' || github.event.inputs.force_build == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh

      - name: Check new patch Morphe (YouTube, Music, Reddit)
        id: check-morphe
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh MorpheApp/morphe-patches latest youtube-morphe.apk

      - name: Check new patch Instagram (Piko MPP)
        id: check-instagram
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko latest instagram-arm64-v8a-morphe.apk

  patch_apps:
    name: Trigger Build Pipeline
    needs: check
    if: ${{ needs.check.outputs.force_run == 'true' || needs.check.outputs.check_morphe == '1' || needs.check.outputs.check_instagram == '1' }}
    uses: ./.github/workflows/manual-patch.yml
    secrets: inherit
    with:
      app: 'all'
